### ISSUE TITLE
[BUG] - Adding multiple Emergency Contacts

### ISSUE THREAD

**Issue by Dibbey** [CloudTheWolf/SAMS-MDT-ISSUE-TRACKER#2]
**Summary:**
I tried adding multiple Emergency Contacts to a Patient and got a "BadMethodCallException" error page.
![Error1](https://user-images.githubusercontent.com/107942951/185956003-726bf077-2fca-4409-bbd8-59873fb97fa2.png)
![Error2](https://user-images.githubusercontent.com/107942951/185956007-336876c4-d0dd-4188-bc7f-0d83fcfd418d.png)

When going back to the "Edit Patient" page, it has added the FIRST patient of the multiple selected ones but not the others.
So say you want to add Patient A and B, once you try to add them and get the error it successfully added Patient A but not B or any after that.

**Steps to Reproduce:**
1. Go to edit a patient's information
2. Under Emergency Contacts select more than 2 people then press "Add Contact".

**Expected Results:**
I guess the expected result should be that all listed ECs get added to the Emergency Contact list for the patient.

**Actual Results:**
An Error page and only the First listed EC from multiple gets added.

**Comment by CloudTheWolf** [comment]
Issue found when we check if the contact already exists.
Fixed!
