### ISSUE TITLE
 [SUGGESTION] - Streamline Editing Patient Details

### ISSUE THREAD

**Issue by Dibbey** [CloudTheWolf/SAMS-MDT-ISSUE-TRACKER#3]
**Is your feature request related to a problem? Please describe.**
When writing information to the "Allergy Information" and "Patient Notes" while on the "Edit Patient" page, if you click "Save Patient Details" or "Save Patient Notes" it will save only either of the two, resulting in the other box to be empty.

So basically when I put in that the patient is allergic to Acetaminophen, then add a Patient Note about that the patient has a medication prescription for something, once I hit save on either, it'll only save _that_ box.

**Summary:**
Maybe instead of two Save buttons there could just be one with the Patient notes attached to the Patient details. Or alternatively combine the two fillable boxes into one resulting in a "Allergy Information/Patient Notes".

**Reason:**
When trying to submit multiple notes into Allergies and then Patient Notes, if you don't know that it will save only one of the two boxes it could result in a lot of information vanishing into the void and having to re-write the information that was filled in.

**Additional context**
It's about these two boxes:
![image](https://user-images.githubusercontent.com/107942951/185959986-c952e2c1-2685-4686-916f-66a4b5e8120c.png)

**Comment by CloudTheWolf** [comment]
Edit Patient Details and Patient Notes merged into a single form, so only 1 save is needed
